name: GAMYAM Answers

on:
  workflow_dispatch:

jobs:
  run-answers:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python answer_post.py
