name: TEST Scheduler

'on':
  workflow_dispatch:

  schedule:
    - cron: '2 12  * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Time
        run: |
          echo "Scheduler Working"
          date
